### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"css selector","selector":"._3F6QL _2WovP"}

### ISSUE THREAD

**Issue by roncat** [devaprender/bot_whatsapp_envio_mensagens#1]
Utilizei o código para entender a lógica do bot mas estou com o seguinte erro:

Ao executar: python3 zapbot.py 
Tudo funciona bem mas na hora de inserir a mensagem na caixa dá um erro:
# python3 zapbot.py

zapbot.py:14: DeprecationWarning: use options instead of chrome_options
  executable_path=r'./chromedriver', chrome_options=options)
Traceback (most recent call last):
  File "zapbot.py", line 38, in <module>
    bot.EnviarMensagens()
  File "zapbot.py", line 26, in EnviarMensagens
    chat_box = self.driver.find_element_by_class_name("_3F6QL _2WovP")
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"._3F6QL _2WovP"}
  (Session info: chrome=80.0.3987.163)

Na inspeção do elemento está assim: 
<div tabindex="-1" class="_3F6QL _2WovP"><div class="_39LWd" style="visibility: visible;">Type a message</div><div class="_2S1VP copyable-text selectable-text" contenteditable="true" data-tab="1" dir="ltr" spellcheck="true"></div></div>

Que aparentemente está correto. Alguém saberia me dizer onde estou errando

**Comment by Jhonatan-de-Souza** [comment]
atualizado
